### ISSUE TITLE
using bin/check-process-restart.rb options results in comparison error

### ISSUE THREAD

**Issue by ZyanKLee** [sensu-plugins/sensu-plugins-process-checks#9]
```ruby
# bin/check-process-restart.rb -w 2 -c 3
Check failed to run: comparison of Fixnum with String failed, ["/var/lib/gems/1.9.1/gems/sensu-plugins-process-checks-0.0.1/bin/check-process-restart.rb:108:in `>='", "/var/lib/gems/1.9.1/gems/sensu-plugins-process-checks-0.0.1/bin/check-process-restart.rb:108:in `run'", "/var/lib/gems/1.9.1/gems/sensu-plugin-1.1.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"]
```

**Comment by ZyanKLee** [comment]
this should fix it:

```
--- /tmp/check-process-restart.rb.orig	2015-05-18 10:06:34.067406060 +0200
+++ /var/lib/gems/1.9.1/gems/sensu-plugins-process-checks-0.0.1/bin/check-process-restart.rb	2015-05-18 10:04:51.503402160 +0200
@@ -105,8 +105,8 @@
     end
     message JSON.generate(checkrestart_out)
     found = checkrestart_out[:found].to_i
-    warning if found >= config[:warn] && found < config[:crit]
-    critical if found >= config[:crit]
+    warning if found >= config[:warn].to_i && found < config[:crit].to_i
+    critical if found >= config[:crit].to_i
     ok
   end
 end
```

**Comment by mattyjones** [comment]
@ZyanKLee  Submit a PR if you would like!

I will also try and make a fix for this when I have some free time.
Thanks!

**Comment by ZyanKLee** [comment]
I could do that earliest in a few weeks, as I'm not at home and due to this
without a computer for some time.
So if you hadn't had the time to fix it, I will submit the PR.

Matt Jones <notifications@github.com> schrieb am Fr., 5. Juni 2015 00:05:

**Comment by ZyanKLee** [comment]
sooo. finally the PR is in a worthy shape. Changelog is changed and fixed for good.
